// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLix4E5Z3dSna8spD2Kkw2Iav3g4ZcoUw',
    appId: '1:249897394934:web:3d20e71e216a7c029402d7',
    messagingSenderId: '249897394934',
    projectId: 'fir-tutorial-708dd',
    authDomain: 'fir-tutorial-708dd.firebaseapp.com',
    storageBucket: 'fir-tutorial-708dd.firebasestorage.app',
    measurementId:
        'G-XXXXXXXXXX', // Add your actual measurement ID from Firebase console
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMLkypcHlrCkZr6Ns8batF_k19h0QbdIc',
    appId: '1:249897394934:android:cfd6abdc0e30001d9402d7',
    messagingSenderId: '249897394934',
    projectId: 'fir-tutorial-708dd',
    storageBucket: 'fir-tutorial-708dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZo-_wLhFnqYAfZD1tgiaXvYCPVk4N524',
    appId: '1:249897394934:ios:5091136e89ea9aa09402d7',
    messagingSenderId: '249897394934',
    projectId: 'fir-tutorial-708dd',
    storageBucket: 'fir-tutorial-708dd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZo-_wLhFnqYAfZD1tgiaXvYCPVk4N524',
    appId: '1:249897394934:ios:5091136e89ea9aa09402d7',
    messagingSenderId: '249897394934',
    projectId: 'fir-tutorial-708dd',
    storageBucket: 'fir-tutorial-708dd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
